# Generated by Django 6.0.3 on 2026-03-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationtype",
            name="name",
            field=models.CharField(
                choices=[("income", "Доход"), ("expense", "Расход")],
                max_length=100,
                unique=True,
            ),
        ),
    ]
