# Generated by Django 6.0.3 on 2026-03-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_operationtype_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationtype",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
